export default {
    NoImg: require("../assets/countryFlags/NOIMG.png"),
    WestIndies: require("../assets/countryFlags/West Indies.png"),
    NewZealand: require("../assets/countryFlags/New Zealand.png"),
    Zimbabwe: require("../assets/countryFlags/Zimbabwe.jpeg"),
    India: require("../assets/countryFlags/India.png"),
    Singapore: require("../assets/countryFlags/Singapore.png"),
    UnitedArabEmirates: require("../assets/countryFlags/United Arab Emirates.png"),
    WelshFireMen: require("../assets/countryFlags/Welsh Fire (Men).jpeg"),
    SouthernBraveMen: require("../assets/countryFlags/Southern Brave (Men).png"),
    Warwickshire: require("../assets/countryFlags/Warwickshire.png"),
    Somerset: require("../assets/countryFlags/Somerset.png"),
    Sussex: require("../assets/countryFlags/Sussex.png"),
    Middlesex: require("../assets/countryFlags/Middlesex.png"),
    Nottinghamshire: require("../assets/countryFlags/Nottinghamshire.png"),
    Surrey: require("../assets/countryFlags/Surrey.png"),
    Northamptonshire: require("../assets/countryFlags/Northamptonshire.png"),
    Derbyshire: require("../assets/countryFlags/Derbyshire.png"),
    Leicestershire: require("../assets/countryFlags/Leicestershire.png"),
    Durham: require("../assets/countryFlags/Durham.png"),
    Yorkshire: require("../assets/countryFlags/Yorkshire.png"),
    Hampshire: require("../assets/countryFlags/Hampshire.png"),
    Kent: require("../assets/countryFlags/Kent.png"),
    Lancashire: require("../assets/countryFlags/Lancashire.png"),
    Worcestershire: require("../assets/countryFlags/Worcestershire.png"),
    Glamorgan: require("../assets/countryFlags/Glamorgan.png"),
    HongKong: require("../assets/countryFlags/Hong Kong.png"),
    Kuwait: require("../assets/countryFlags/Kuwait.png"),
    OvalInvinciblesMen: require("../assets/countryFlags/Oval Invincibles (Men).png"),
    BirminghamPhoenixMen: require("../assets/countryFlags/Birmingham Phoenix (Men).png"),
    LondonSpiritMen: require("../assets/countryFlags/London Spirit (Men).png"),
    Kenya: require("../assets/countryFlags/Kenya.png"),
    Nepal: require("../assets/countryFlags/Nepal.png"),
    England: require("../assets/countryFlags/England.png"),
    SouthAfrica: require("../assets/countryFlags/South Africa.jpeg"),
    TrentRocketsMen: require("../assets/countryFlags/Trent Rockets (Men).png"),
    NSChargers: require("../assets/countryFlags/N S-Chargers.png"),
    Afghanistan: require("../assets/countryFlags/Afghanistan.jpeg"),
    SriLanka: require("../assets/countryFlags/Sri Lanka.png"),
    Australia: require("../assets/countryFlags/Australia.png"),
    Pakistan: require("../assets/countryFlags/Pakistan.png"),
    ManchesterOriginalsMen: require("../assets/countryFlags/Manchester Originals (Men).png"),
    Sindh: require("../assets/countryFlags/Sindh.png"),
    SouthernPunjabPakistan: require("../assets/countryFlags/Southern Punjab (Pakistan).jpeg"),
    CentralPunjabPakistan: require("../assets/countryFlags/Central Punjab (Pakistan).png"),
    Bangladesh: require("../assets/countryFlags/Bangladesh.png"),
    JamaicaTallawahs: require("../assets/countryFlags/Jamaica Tallawahs.png"),
    KhyberPakhtunkhwa: require("../assets/countryFlags/Khyber Pakhtunkhwa.jpeg"),
    StLuciaKings: require("../assets/countryFlags/St Lucia Kings.png"),
    TBC: require("../assets/countryFlags/TBC.jpeg"),
    Gloucestershire: require("../assets/countryFlags/Gloucestershire.png"),
    Essex: require("../assets/countryFlags/Essex.jpeg"),
    BarbadosRoyals: require("../assets/countryFlags/Barbados Royals.jpeg"),
    TrinbagoKnightRiders: require("../assets/countryFlags/Trinbago Knight Riders.png"),
    KurunegalaY: require("../assets/countryFlags/Kurunegala Y.jpeg"),
    NugegodaSWC: require("../assets/countryFlags/Nugegoda SWC.jpeg"),
    SriLankaArmySportsClub: require("../assets/countryFlags/Sri Lanka Army Sports Club.jpeg"),
    NondescriptsCricketClub: require("../assets/countryFlags/Nondescripts Cricket Club.jpeg"),
    BadureliyaSportsClub: require("../assets/countryFlags/Badureliya Sports Club.jpeg"),
    GalleCricketClub: require("../assets/countryFlags/Galle Cricket Club.jpeg"),
    Bloomfield: require("../assets/countryFlags/Bloomfield.png"),
    TamilUnion: require("../assets/countryFlags/Tamil Union.png"),
    LankanCricketClub: require("../assets/countryFlags/Lankan Cricket Club.jpeg"),
    SinhaleseSportsClub: require("../assets/countryFlags/Sinhalese Sports Club.jpeg"),
    SebastCAC: require("../assets/countryFlags/Sebast CAC.jpeg"),
    KandyCustomsCricketClub: require("../assets/countryFlags/Kandy Customs Cricket Club.jpeg"),
    PanaduraSportsClub: require("../assets/countryFlags/Panadura Sports Club.jpeg"),
    Chilaw: require("../assets/countryFlags/Chilaw.jpeg"),
    SriLankaNavySportsClub: require("../assets/countryFlags/Sri Lanka Navy Sports Club.jpeg"),
    UnitedArabEmirates: require("../assets/countryFlags/United Arab Emirates.png"),
    England: require("../assets/countryFlags/England.png"),
    Warwickshire: require("../assets/countryFlags/Warwickshire.png"),
    Essex: require("../assets/countryFlags/Essex.jpeg"),
    Middlesex: require("../assets/countryFlags/Middlesex.png"),
    Gloucestershire: require("../assets/countryFlags/Gloucestershire.png"),
    Singapore: require("../assets/countryFlags/Singapore.png"),
    Netherlands: require("../assets/countryFlags/Netherlands.png"),
    WestIndies: require("../assets/countryFlags/West Indies.png"),
    Netherlands: require("../assets/countryFlags/Netherlands.png"),
    Middlesex: require("../assets/countryFlags/Middlesex.png"),
    Warwickshire: require("../assets/countryFlags/Warwickshire.png"),
    Surrey: require("../assets/countryFlags/Surrey.png"),
    Gloucestershire: require("../assets/countryFlags/Gloucestershire.png"),
    WestIndies: require("../assets/countryFlags/West Indies.png"),
    Bahrain: require("../assets/countryFlags/Bahrain.png"),
    Surrey: require("../assets/countryFlags/Surrey.png"),
    Derbyshire: require("../assets/countryFlags/Derbyshire.png"),
    Kent: require("../assets/countryFlags/Kent.png"),
    Northamptonshire: require("../assets/countryFlags/Northamptonshire.png"),
    Worcestershire: require("../assets/countryFlags/Worcestershire.png"),
    Gloucestershire: require("../assets/countryFlags/Gloucestershire.png"),
    Leicestershire: require("../assets/countryFlags/Leicestershire.png"),
    Glamorgan: require("../assets/countryFlags/Glamorgan.png"),
    Lancashire: require("../assets/countryFlags/Lancashire.png"),
    Yorkshire: require("../assets/countryFlags/Yorkshire.png"),
    Warwickshire: require("../assets/countryFlags/Warwickshire.png"),
    Nottinghamshire: require("../assets/countryFlags/Nottinghamshire.png"),
    centralpunjab: require("../assets/countryFlags/central punjab.png"),
    cookislands: require("../assets/countryFlags/cook islands.png"),
    fiji: require("../assets/countryFlags/fiji.png"),
    guyanaamazonwarriors: require("../assets/countryFlags/guyana amazon warriors.png"),
    PapuaNewGuinea: require("../assets/countryFlags/Papua New Guinea.png"),
    samoa: require("../assets/countryFlags/samoa.png"),
    sourthernpunjab: require("../assets/countryFlags/sourthern punjab.png"),
    southafrica: require("../assets/countryFlags/south africa.png"),
    unitedstatesofamerica: require("../assets/countryFlags/united states of america.png"),
    vanuatu: require("../assets/countryFlags/vanuatu.jpg"),
    botswana: require("../assets/countryFlags/botswana.png"),
    cameroon: require("../assets/countryFlags/cameroon.png"),
    malawi: require("../assets/countryFlags/malawi.png"),
    southzone: require("../assets/countryFlags/south zone.png"),
    uganda: require("../assets/countryFlags/uganda.png"),
    westzone: require("../assets/countryFlags/west zone.png"),
    centralzone: require("../assets/countryFlags/central zone.jpeg"),
    srilankaarmysportsclub: require("../assets/countryFlags/srilanka army sports club.png"),
    negombocricketclub: require("../assets/countryFlags/negombo cricket club.png"),
    baduraliyasportsclub: require("../assets/countryFlags/baduraliya sports club.jpeg"),
    BurgherRecreationClub: require("../assets/countryFlags/burgher recreation club.jpeg"),
    ColomboCricketClub: require("../assets/countryFlags/colombo cricket club.jpeg"),
    MoorsSportsClub: require("../assets/countryFlags/moors sports club.jpeg"),
    nondiscriptcricketclub: require("../assets/countryFlags/nondiscript cricket club.jpeg"),
    PoliceSportsClub: require("../assets/countryFlags/police sports club.jpeg"),
    RagamaCricketClub: require("../assets/countryFlags/ragama cricket club.jpeg"),
    SaracensSportsClub: require("../assets/countryFlags/saracens sports club.jpeg"),
    ghana: require("../assets/countryFlags/ghana.png"),
    mozambique: require("../assets/countryFlags/mozambique.png"),
    uganda: require("../assets/countryFlags/uganda.png"),
}